bitrise-steplib/bitrise-step-activate-gradle-remote-cache

- step/step.go
> feat: hardcode deployed cache endpoint

- README.md
- step.yml
Add step description and generate README using the `generate_readme` workflow.
> Add README

- README.md
- e2e/bitrise.yml
- step.yml
- step/init.gradle.gotemplate
- step/initscript.go
- step/initscript_test.go
- step/step.go
- step/step_test.go
Requires a *MINOR* [version update](https://semver.org/)
Relevant PR in the Gradle plugin with more context: https://github.com/bitrise-io/gradle-remote-cache/pull/48
- Add a new input for the validation level setting
- Wire this input to the config field of the Gradle plugin
> Add validation level input

- bitrise.yml
- step/checks.go
- step/step.go
- step/step_test.go
If the complete feature is not enabled for the given workspace, the step should not do its thing and just print a warning.
Check the existence of a feature flag and if it's not available, print a warning both to the log and as a build annotation.
> Add feature gate

- step.yml
Related Jira ticket: https://bitrise.atlassian.net/browse/ACI-1180
> [ACI-1180] disables metrics collection by default

- step.sh
> chore: Bump CLI version to v0.8.2

- step.sh
> chore: Bump CLI version to 0.8.3

- step.sh
> feat: Use CLI 0.9.0

- step.sh
> chore: Bump CLI to 0.10.0

- step.sh
Update CLI version that uses gradle remote cache plugin 1.2.3, improving cache performance
> feat: Use CLI version 0.11.0

- step.sh
Use CLI v0.12.0 which includes performance improvements
> feat: Use CLI v0.12.0

- step.sh
> feat: Bump CLI to ensure plugins use the same invocation ID

- e2e/bitrise.yml
- step.sh
> feat: Bump CLI to support Android Studio for local development

- step.sh
> chore: Bump CLI to 0.14.1

- step.sh
> feat: Bump CLI to ensure cache plugin reuses the same invocation ID

- step.sh
Requires a *MINOR* [version update](https://semver.org/)
> [ACI-1586] Wire in inputs

- step.sh
> ACI-2386 - Added ORD endpoint

- step.sh
> chore: Update CLI to 0.14.7

- step.sh
Requires a *PATCH* [version update](https://semver.org/)
Updates the CLI version to v0.15.2
> Update CLI to v0.15.2

- step.yml
> feat: Make title shorter

- step.sh
Reverts bitrise-steplib/bitrise-step-activate-gradle-remote-cache#47
> Revert "Bump CLI version to v0.15.3"

- step.sh
Update CLI version to v0.15.4
Requires a *PATCH* [version update](https://semver.org/)
> Bump CLI version to v0.15.4

- step.sh
> feat: Bump CLI to improve initialization and DC configuration

- step.sh
> feat: Bump CLI for Gradle 8.12 compatibility

- step.sh
> feat: Bump CLI to log plugin versions and fix build tool header

- step.sh
> feat: Bump CLI to fix version logging

- step.sh
> feat: ACI-3384 Download from GAR if GH fails

- README.md
- step.sh
> chore: Bump CLI
